# doet nog niet veel
# in seconds
summonPotion_Cooldown: 30
summonArrow_Cooldown: 1
summonBeast_Cooldown: 300
summonFlame_Cooldown: 5
summonExplosion_Cooldown: 10

# 2 = 1 hunger bar
summonLightning_Food_Penalty: 6
summonPotion_Food_Penalty: 2
summonArrow_Food_Penalty: 1
summonBeast_Food_Penalty: 4
summonFlame_Food_Penalty: 4
summonExplosion_Food_Penalty: 4

#Other settings
summonFlame_Knockback_Level: 1.5
summonArrow_damage: 3