name: WandPlugin
version: '${project.version}'
main: me.sovjetelmo.wandplugin.Wandplugin
api-version: '1.20'
commands:
  magicwand:
    description: Give a magic wand to the player
    usage: /<command> <wandType>
  mw:
    description: Open the wand selection GUI
    usage: /<command>
  mwconfig:
    description: Open the spell configuration GUI
    usage: /<command>